<?php
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/includes/layout.php';
$dateFrom=$_GET['date_from']??date('Y-m-01');$dateTo=$_GET['date_to']??date('Y-m-d');
$where="payment_status='Paid'";$params=[];if($dateFrom!==''){$where.=' AND DATE(payment_date)>=?';$params[]=$dateFrom;}if($dateTo!==''){$where.=' AND DATE(payment_date)<=?';$params[]=$dateTo;}
$metrics=$pdo->prepare("SELECT COUNT(*) paid_transactions, COALESCE(SUM(amount),0) total_revenue, COALESCE(AVG(amount),0) average_order FROM payments WHERE $where");$metrics->execute($params);$metrics=$metrics->fetch();
$vendorSql="SELECT v.vendor_id,v.stall_name,COALESCE(SUM(p.amount),0) total_revenue,COUNT(p.payment_id) transaction_count FROM vendors v LEFT JOIN payments p ON p.vendor_id=v.vendor_id AND p.payment_status='Paid'";$joinParams=[];if($dateFrom!==''){$vendorSql.=' AND DATE(p.payment_date)>=?';$joinParams[]=$dateFrom;}if($dateTo!==''){$vendorSql.=' AND DATE(p.payment_date)<=?';$joinParams[]=$dateTo;}$vendorSql.=' GROUP BY v.vendor_id,v.stall_name ORDER BY total_revenue DESC';$stmt=$pdo->prepare($vendorSql);$stmt->execute($joinParams);$vendorData=$stmt->fetchAll();
$best=$vendorData[0]??null;$lowest=null;foreach(array_reverse($vendorData) as $row){if((float)$row['total_revenue']>0){$lowest=$row;break;}}
$monthlyStmt=$pdo->prepare("SELECT DATE(payment_date) label,COALESCE(SUM(amount),0) total FROM payments WHERE $where GROUP BY DATE(payment_date) ORDER BY DATE(payment_date)");$monthlyStmt->execute($params);$daily=$monthlyStmt->fetchAll();
admin_header('System Analytics & Reports','analytics');
?>
<form method="get" class="filter-bar row g-2 align-items-end"><div class="col-md-4"><label class="form-label mb-1">From Date</label><input class="form-control" type="date" name="date_from" value="<?= e($dateFrom) ?>"></div><div class="col-md-4"><label class="form-label mb-1">To Date</label><input class="form-control" type="date" name="date_to" value="<?= e($dateTo) ?>"></div><div class="col-md-4"><button class="btn btn-brand w-100">Generate Report</button></div></form>
<div class="row g-3 mb-4"><div class="col-md-4"><div class="stat-card"><div class="label">Total Paid Revenue</div><div class="value">RM <?= number_format((float)$metrics['total_revenue'],2) ?></div><div class="note">Selected date range</div></div></div><div class="col-md-4"><div class="stat-card"><div class="label">Successful Transactions</div><div class="value"><?= number_format($metrics['paid_transactions']) ?></div><div class="note">Payments marked as Paid</div></div></div><div class="col-md-4"><div class="stat-card"><div class="label">Average Transaction</div><div class="value">RM <?= number_format((float)$metrics['average_order'],2) ?></div><div class="note">Average paid payment value</div></div></div></div>
<div class="row g-4"><div class="col-xl-7"><section class="panel"><h2 class="panel-title">Revenue by Vendor</h2><div class="chart-wrap"><canvas id="vendorChart"></canvas></div></section></div><div class="col-xl-5"><section class="panel"><h2 class="panel-title">Performance Summary</h2><div class="mb-4"><div class="text-secondary small mb-1">Best Performing Vendor</div><?php if($best): ?><strong class="fs-5"><?= e($best['stall_name']) ?></strong><div class="mt-1">RM <?= number_format((float)$best['total_revenue'],2) ?> · <?= e($best['transaction_count']) ?> paid transaction(s)</div><?php else:?><div class="text-secondary">No data found for the selected criteria.</div><?php endif;?></div><div><div class="text-secondary small mb-1">Lowest Performing Vendor With Sales</div><?php if($lowest): ?><strong class="fs-5"><?= e($lowest['stall_name']) ?></strong><div class="mt-1">RM <?= number_format((float)$lowest['total_revenue'],2) ?> · <?= e($lowest['transaction_count']) ?> paid transaction(s)</div><?php else:?><div class="text-secondary">No paid sales data available.</div><?php endif;?></div></section></div></div>
<section class="panel mt-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="panel-title mb-0">Vendor Revenue Details</h2><form method="post" action="save_report.php"><input type="hidden" name="date_from" value="<?= e($dateFrom) ?>"><input type="hidden" name="date_to" value="<?= e($dateTo) ?>"><input type="hidden" name="total_sales" value="<?= e($metrics['total_revenue']) ?>"><input type="hidden" name="best_vendor_id" value="<?= e($best['vendor_id']??'') ?>"><input type="hidden" name="lowest_vendor_id" value="<?= e($lowest['vendor_id']??'') ?>"><button class="btn btn-outline-primary btn-sm">Save Report Record</button></form></div><div class="table-responsive"><table class="table table-hover"><thead><tr><th>Rank</th><th>Vendor</th><th>Paid Transactions</th><th>Total Revenue</th></tr></thead><tbody><?php if(!$vendorData): ?><tr><td colspan="4" class="empty-state">No vendor data available.</td></tr><?php endif; ?><?php foreach($vendorData as $i=>$v): ?><tr><td><?= $i+1 ?></td><td><?= e($v['stall_name']) ?></td><td><?= e($v['transaction_count']) ?></td><td>RM <?= number_format((float)$v['total_revenue'],2) ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script><script>new Chart(document.getElementById('vendorChart'),{type:'bar',data:{labels:<?= json_encode(array_column($vendorData,'stall_name')) ?>,datasets:[{label:'Revenue (RM)',data:<?= json_encode(array_map('floatval',array_column($vendorData,'total_revenue'))) ?>,backgroundColor:'#004AAD',borderRadius:7}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true}}}});</script>
<?php admin_footer(); ?>
