<?php
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/includes/layout.php';
$status = $_GET['status'] ?? ''; $vendor = (int)($_GET['vendor_id'] ?? 0); $dateFrom=$_GET['date_from']??''; $dateTo=$_GET['date_to']??'';
$sql="SELECT p.*,c.name customer_name,v.stall_name,o.order_status FROM payments p JOIN customers c ON c.cust_id=p.cust_id JOIN vendors v ON v.vendor_id=p.vendor_id JOIN orders o ON o.order_id=p.order_id"; $where=[];$params=[];
if(in_array($status,['Pending Payment','Paid','Failed','Refunded'],true)){ $where[]='p.payment_status=?';$params[]=$status; }
if($vendor>0){$where[]='p.vendor_id=?';$params[]=$vendor;}
if($dateFrom!==''){$where[]='DATE(p.payment_date)>=?';$params[]=$dateFrom;}
if($dateTo!==''){$where[]='DATE(p.payment_date)<=?';$params[]=$dateTo;}
if($where)$sql.=' WHERE '.implode(' AND ',$where);$sql.=' ORDER BY p.payment_date DESC';$stmt=$pdo->prepare($sql);$stmt->execute($params);$payments=$stmt->fetchAll();$vendors=$pdo->query('SELECT vendor_id,stall_name FROM vendors ORDER BY stall_name')->fetchAll();
admin_header('Payment Monitoring','payments');
?>
<form method="get" class="filter-bar row g-2 align-items-end"><div class="col-md-3"><label class="form-label mb-1">Payment Status</label><select class="form-select" name="status"><option value="">All statuses</option><?php foreach(['Pending Payment','Paid','Failed','Refunded'] as $s): ?><option value="<?= e($s) ?>" <?= $status===$s?'selected':'' ?>><?= e($s) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label mb-1">Vendor</label><select class="form-select" name="vendor_id"><option value="">All vendors</option><?php foreach($vendors as $v): ?><option value="<?= $v['vendor_id'] ?>" <?= $vendor===$v['vendor_id']?'selected':'' ?>><?= e($v['stall_name']) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label class="form-label mb-1">From Date</label><input class="form-control" type="date" name="date_from" value="<?= e($dateFrom) ?>"></div><div class="col-md-2"><label class="form-label mb-1">To Date</label><input class="form-control" type="date" name="date_to" value="<?= e($dateTo) ?>"></div><div class="col-md-2"><button class="btn btn-brand w-100">Filter Payments</button></div></form>
<section class="panel"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="panel-title mb-0">Transactions</h2><span class="text-secondary small"><?= count($payments) ?> record(s)</span></div><div class="table-responsive"><table class="table table-hover"><thead><tr><th>Payment ID</th><th>Order</th><th>Customer</th><th>Vendor</th><th>Method</th><th>Amount</th><th>Payment Date</th><th>Payment Status</th><th>Order Status</th></tr></thead><tbody><?php if(!$payments): ?><tr><td colspan="9" class="empty-state">No payment records available for these filters.</td></tr><?php endif; ?><?php foreach($payments as $p): ?><tr><td>#<?= e($p['payment_id']) ?></td><td>#<?= e($p['order_id']) ?></td><td><?= e($p['customer_name']) ?></td><td><?= e($p['stall_name']) ?></td><td><?= e($p['payment_method']) ?></td><td>RM <?= number_format((float)$p['amount'],2) ?></td><td><?= e(date('d M Y, h:i A',strtotime($p['payment_date']))) ?></td><td><?= status_badge($p['payment_status']) ?></td><td><?= status_badge($p['order_status']) ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php admin_footer(); ?>
