<?php
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/includes/layout.php';
$flash='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    $action=$_POST['action']??'';$id=(int)($_POST['review_id']??0);
    if(in_array($action,['Visible','Hidden'],true)){$pdo->prepare('UPDATE reviews SET review_status=? WHERE review_id=?')->execute([$action,$id]);$flash='Review status updated successfully.';}
    elseif($action==='delete'){$pdo->prepare('DELETE FROM reviews WHERE review_id=?')->execute([$id]);$flash='Review deleted successfully.';}
}
$status=$_GET['status']??'';$rating=(int)($_GET['rating']??0);$vendor=(int)($_GET['vendor_id']??0);$sql='SELECT r.*,c.name customer_name,v.stall_name FROM reviews r JOIN customers c ON c.cust_id=r.cust_id JOIN vendors v ON v.vendor_id=r.vendor_id';$where=[];$params=[];
if(in_array($status,['Visible','Hidden','Pending'],true)){$where[]='r.review_status=?';$params[]=$status;}if($rating>=1&&$rating<=5){$where[]='r.rating=?';$params[]=$rating;}if($vendor>0){$where[]='r.vendor_id=?';$params[]=$vendor;}if($where)$sql.=' WHERE '.implode(' AND ',$where);$sql.=' ORDER BY r.review_id DESC';$stmt=$pdo->prepare($sql);$stmt->execute($params);$reviews=$stmt->fetchAll();$vendors=$pdo->query('SELECT vendor_id,stall_name FROM vendors ORDER BY stall_name')->fetchAll();
admin_header('Review Moderation','reviews');
?>
<?php if($flash): ?><div class="alert alert-success"><?= e($flash) ?></div><?php endif; ?>
<form method="get" class="filter-bar row g-2 align-items-end"><div class="col-md-3"><label class="form-label mb-1">Review Status</label><select class="form-select" name="status"><option value="">All statuses</option><?php foreach(['Pending','Visible','Hidden'] as $s): ?><option <?= $status===$s?'selected':'' ?>><?= $s ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label class="form-label mb-1">Rating</label><select class="form-select" name="rating"><option value="">All ratings</option><?php for($i=5;$i>=1;$i--): ?><option value="<?= $i ?>" <?= $rating===$i?'selected':'' ?>><?= $i ?> star</option><?php endfor; ?></select></div><div class="col-md-4"><label class="form-label mb-1">Vendor</label><select class="form-select" name="vendor_id"><option value="">All vendors</option><?php foreach($vendors as $v): ?><option value="<?= $v['vendor_id'] ?>" <?= $vendor===$v['vendor_id']?'selected':'' ?>><?= e($v['stall_name']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><button class="btn btn-brand w-100">Filter Reviews</button></div></form>
<section class="panel"><h2 class="panel-title">Customer Reviews</h2><div class="table-responsive"><table class="table table-hover"><thead><tr><th>Review</th><th>Customer</th><th>Vendor</th><th>Rating</th><th>Status</th><th class="text-end">Moderation</th></tr></thead><tbody><?php if(!$reviews): ?><tr><td colspan="6" class="empty-state">No review available for these filters.</td></tr><?php endif; ?><?php foreach($reviews as $r): ?><tr><td style="min-width:240px"><?= e($r['comment'] ?: 'No written comment.') ?></td><td><?= e($r['customer_name']) ?></td><td><?= e($r['stall_name']) ?></td><td><?= str_repeat('★',$r['rating']) ?><span class="text-secondary"><?= str_repeat('☆',5-$r['rating']) ?></span></td><td><?= status_badge($r['review_status']) ?></td><td class="text-end"><form method="post" class="d-inline"><input type="hidden" name="review_id" value="<?= $r['review_id'] ?>"><button name="action" value="Visible" class="btn btn-sm btn-outline-success">Keep</button><button name="action" value="Hidden" class="btn btn-sm btn-outline-secondary">Hide</button><button name="action" value="delete" class="btn btn-sm btn-outline-danger" onclick="return confirm('Delete this review permanently?')">Delete</button></form></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php admin_footer(); ?>
